
include ../.applTop
include $(APPLIC_TOP)/config/CONFIG

# The resource.def will be placed in the data directory
DATA    = $(wildcard ../resource.def)

# The *.vws scripts will be edited and put in the bin/$(T_A) directory
PROD    = $(patsubst ../%.vws, %, $(wildcard ../*.vws))

include $(APPLIC_TOP)/config/RULES.Build
