#!/usr/local/bin/tcsh -f
#
# checkoutSim
#
# Description:
#
#   This sets the environment variables and runs the checkout test
#   SIMULATION VERSION
#
#   It is assumed this script is being run from the "test" directory
#   and that wish4.2 is in the current PATH.
#
# Invocation:
#
#   checkoutSim name -auto -debug
#
#   where name is the name of the entity to be checked out.
#   -auto (optional) runs the script automatically
#   -debug (optional) adds diagnostic messages useful for debugging a script
#

#
# Bail out if the scripts directory does not exist.
#
if ( !(-e scripts) ) then

   echo "Please cd to the 'test' directory before running this script." 
   exit
endif

#
# Save the current day
#

set day = `date +%d%h%y`

#
# Create the "logfiles" directory for the current day if it doesn't exist.
#
if ( !(-e ./logfiles) ) then

   echo "Creating logfiles directory..." 
   mkdir logfiles
endif

if (!(-e ./logfiles/$day)) then

    mkdir ./logfiles/$day
endif

#
# Update the barcode files in the simulation directory from the ones
# in the main directory.
#
\cp /gemini/gmos/lut/msk.lut /gemini/gmos/lut/sim
\cp /gemini/gmos/lut/flt.lut /gemini/gmos/lut/sim
\cp /gemini/gmos/lut/gr.lut /gemini/gmos/lut/sim

#
# Define the environment variable pointing to the config files
#
setenv DEFAULT_CONFIG_DIR ./configFilesSim

#
# Run the tests
#
wish4.2 ./dhsTestCmdr.tk -a scripts/${1}Checkout.asm -i scripts/${1}Checkout.scr $2 $3

#
# Move the log file generated into the "logfiles" directory
# Logfiles made in simulation mode have the string "Sim" appended
# to their name.
#
\mv ./scripts/${1}Checkout.scr.log ./logfiles/${day}/${1}CheckoutSim.log

#
# Make a backup copy of the log file with the current date and time appended
#
\cp ./logfiles/${day}/${1}CheckoutSim.log ./logfiles/${day}/${1}CheckoutSim.log.`date +%H:%M:%S-%d-%h-20%y`
