#!/usr/local/bin/tcsh -f
#
# crosstalkYNolog
#
# Description:
#
#   A simple script to check out how the X stage position varies when the Y stage is moved
#
#   It is assumed this script is being run from the "test" directory.
#   The translation assembly and detector controller must already have been initalised
#   and set into the desired configuration.
#
# Invocation:
#   crosstalkYNolog starting-file-number
#
# NOTE:
#   This script is designed to be as simple as possible, so it does not do as much
#   checking as a dhsTestCmdr script. It is designed to generate test data rather
#   than to check out the correct operation of the instrument.
#

#
# Only allow access to the MK hardware if the GMOS_MK_ACCESS environment
# variable has been defined.
#

if (!($?GMOS_MK_ACCESS)) then
    echo ""
    echo "GMOS MK safety check failed."
    echo ""
    echo "Before executing this script, which will move real MK hardware,"
    echo 'you must type "gmosMK" to confirm that it is safe to do so.'
    echo ""
    exit
else
    echo "GMOS MK safety check passed."
endif

#
# Bail out if the scripts directory does not exist.
#
if ( !(-e scripts) ) then

   echo "Please cd to the 'test' directory before running this script." 
   exit
endif

echo "Checking cross talk as Y stage is moved."
date
echo " "
echo "It is assumed you have already configured the detector controller"
echo "and initialized and indexed the translation assembly."

#
# Save the current day
#
set day = `date +%d%h%y`

#
# Log the current instrument configuration
#
echo " "
set maskID = `getChannel gm:sad:cc:mskID`
echo "Current mask ID        = "$maskID
echo "Current mask location  = "`getChannel gm:sad:cc:mskLoc`

set filter1 = `getChannel gm:sad:filtName1`
set filter2 = `getChannel gm:sad:filtName2`
echo "Current filters        = $filter1 and $filter2"
echo "Filter wheel positions = "`getChannel gm:sad:cc:fltPos1`" and "`getChannel gm:sad:cc:fltPos1`

set grating = `getChannel gm:sad:grName`
echo "Current grating name   = "$grating
echo "Ruling density         = "`getChannel gm:sad:grRulingDensity`
echo "Blaze direction        = "`getChannel gm:sad:grBlazeDir`
echo "Central wavelength     = "`getChannel gm:sad:grWavelen`
echo "Order                  = "`getChannel gm:sad:grOrder`

set grID = `getChannel gm:sad:cc:grID`
set grTilt = `getChannel gm:sad:cc:grTilt`
echo "Current grating ID     = "$grID
echo "Current grating tilt   = "$grTilt

#
# Define the measurement parameters:
#
# xpos = fixed X position in microns (centre of travel)
# zpos = fixed Z position in microns (best focus)
# ystart = starting Y position in microns
# ystep  = X increment in microns
# ncount = Number of measurements (xend = ystart + ncounts*ystep)
#

set xpos = 100.0
#set zpos = 4160.0
set zpos = 1835.0

set ymin = -15.0
set ymax = 230.0

set ystart = $ymin
set ystep = 5.0
set ncount = 49
set filecount = $1

echo " "
echo "X position = $xpos microns"
echo "Z position = $zpos microns"
echo "There will be $ncount Y measurements from $ystart microns in $ystep micron increments"

#
# Add column headers to the log file
#
echo " "
echo "--------------------------------------------------------------------------------------------------"
echo "File	Exposure	Grating	Tilt	Filter1	Filter2	MaskId	xpos	ypos	zpos	deltaX(therm)	deltaY(therm)	deltaZ(therm)	deltaX(x-talk)	deltaY(x-talk)"
echo "    	(secs)  	(degrees)   	       	       	      	(um)	(um)	(um)	    (um)     	    (um)     	    (um)     	    (um)      	    (um)"

#
# Move the translation assembly to the centre/best focus position position
#

set moveResponse = `moveAssembly gm:cc:dtaAssembly $xpos 108.0 $zpos`
set moveStatus = `echo $moveResponse | grep 'Command Success'`
if ( $#moveStatus != 2 ) then

   echo "Assembly move failed"
   caget gm:cc:dtaAssembly.MESS
   exit -1
endif

set actualX = `getChannel gm:cc:dta1Device.MPOS`
set actualY = `getChannel gm:cc:dta2Device.MPOS`
set actualZ = `getChannel gm:cc:dta3Device.MPOS`

set dxth = `getChannel gm:cc:dtaAssembly.VALA`
set dyth = `getChannel gm:cc:dtaAssembly.VALB`
set dzth = `getChannel gm:cc:dtaAssembly.VALC`

#
# TEMPORARY ADDITION FOR COLD TESTS
#
set dxx = `getChannel  gm:cc:dtacrossx.VAL`
set dyx = `getChannel  gm:cc:dtacrossy.VAL`


#
# Set the file name
#

set filename = g0${filecount}
set fileResponse = `setObserveFilename gm: ${filename}`
set fileStatus = `echo $fileResponse | grep 'Command Success'`
@ filecount = $filecount + 1
set fileStatus = `echo $fileResponse | grep 'Command Success'`
if ( $#fileStatus != 2 ) then

   echo "Setting filename failed"
   exit -1
endif

#
# Make an observation
#

set observeResponse = `executeObserve gm:`
set observeStatus = `echo $observeResponse | grep 'Command Success'`
if ( $#observeStatus != 2 ) then

   echo "Observation failed"
   exit -1
endif
set exposure = `getChannel gm:sad:dc:exposed`

#
# Log the result
#

echo "$filename	$exposure	$grID	$grTilt	$filter1	$filter2	$maskID	$actualX	$actualY	$actualZ	$dxth	$dyth	$dzth	$dxx	$dyx"

#
# Initialise the translation assembly to the lowest possible Y position
# then increment Y in steps until the whole Y range has been covered.
#

set ypos = $ystart
set count = 0

while ( $count <= $ncount )

#
# Move the Y axis
#

   set moveResponse = `moveAssembly gm:cc:dtaAssembly $xpos $ypos $zpos`
   set moveStatus = `echo $moveResponse | grep 'Command Success'`
   if ( $#moveStatus != 2 ) then

      echo "Assembly move failed at Y = " $ypos
      caget gm:cc:dtaAssembly.MESS
      exit -1
   endif

   set actualX = `getChannel gm:cc:dta1Device.MPOS`
   set actualY = `getChannel gm:cc:dta2Device.MPOS`
   set actualZ = `getChannel gm:cc:dta3Device.MPOS`

   set dxth = `getChannel gm:cc:dtaAssembly.VALA`
   set dyth = `getChannel gm:cc:dtaAssembly.VALB`
   set dzth = `getChannel gm:cc:dtaAssembly.VALC`

#
# TEMPORARY ADDITION FOR COLD TESTS
#
   set dxx = `getChannel  gm:cc:dtacrossx.VAL`
   set dyx = `getChannel  gm:cc:dtacrossy.VAL`

#
# Set the file name
#

   set filename = g0${filecount}
   set fileResponse = `setObserveFilename gm: ${filename}`
   set fileStatus = `echo $fileResponse | grep 'Command Success'`
   @ filecount = $filecount + 1
   if ( $#fileStatus != 2 ) then

      echo "Setting filename failed at X = " $xpos
      exit -1
   endif

#
# Make an observation
#

   set observeResponse = `executeObserve gm:`
   set observeStatus = `echo $observeResponse | grep 'Command Success'`
   if ( $#observeStatus != 2 ) then

      echo "Observation failed at Y = " $ypos
      exit -1
   endif
   set exposure = `getChannel gm:sad:dc:exposed`

#
# Log the result
#

   echo "$filename	$exposure	$grID	$grTilt	$filter1	$filter2	$maskID	$actualX	$actualY	$actualZ	$dxth	$dyth	$dzth	$dxx	$dyx"

#
# Increment the Y axis position by ystep microns, increment the counter and repeat the loop.
#

   set ypos = `add $ypos $ystep`
   @ count = $count + 1
end

#
# Set the translation assembly to the highest possible Y position
# then decrement Y in steps until the whole Y range has been covered.
# again.
#

down:

set ypos = $ymax
set count = 0

echo " "
echo "There will now be $ncount Y measurements from $ypos microns in $ystep micron decrements"

while ( $count <= $ncount )

#
# Move the Y axis
#

   set moveResponse = `moveAssembly gm:cc:dtaAssembly $xpos $ypos $zpos`
   set moveStatus = `echo $moveResponse | grep 'Command Success'`
   if ( $#moveStatus != 2 ) then

      echo "Assembly move failed at Y = " $ypos
      caget gm:cc:dtaAssembly.MESS
      exit -1
   endif

   set actualX = `getChannel gm:cc:dta1Device.MPOS`
   set actualY = `getChannel gm:cc:dta2Device.MPOS`
   set actualZ = `getChannel gm:cc:dta3Device.MPOS`

   set dxth = `getChannel gm:cc:dtaAssembly.VALA`
   set dyth = `getChannel gm:cc:dtaAssembly.VALB`
   set dzth = `getChannel gm:cc:dtaAssembly.VALC`

#
# TEMPORARY ADDITION FOR COLD TESTS
#
   set dxx = `getChannel  gm:cc:dtacrossx.VAL`
   set dyx = `getChannel  gm:cc:dtacrossy.VAL`

#
# Set the file name
#

   set filename = g0${filecount}
   set fileResponse = `setObserveFilename gm: g0${filecount}`
   set fileStatus = `echo $fileResponse | grep 'Command Success'`
   @ filecount = $filecount + 1
   if ( $#fileStatus != 2 ) then

      echo "Setting filename failed at X = " $xpos
      exit -1
   endif

#
# Make an observation
#

   set observeResponse = `executeObserve gm:`
   set observeStatus = `echo $observeResponse | grep 'Command Success'`
   if ( $#observeStatus != 2 ) then

      echo "Observation failed at Y = " $ypos
      exit -1
   endif
   set exposure = `getChannel gm:sad:dc:exposed`

#
# Log the result
#

   echo "$filename	$exposure	$grID	$grTilt	$filter1	$filter2	$maskID	$actualX	$actualY	$actualZ	$dxth	$dyth	$dzth	$dxx	$dyx"

#
# Decrement the Y axis position by ystep microns, increment the counter and repeat the loop.
#

   set ypos = `add $ypos -$ystep`
   @ count = $count + 1
end

echo "Script completed successfully."

exit
