#!/usr/local/bin/tcsh -f
#
# gmosCheckoutSim
#
# Description:
#
#  Run various levels of checkout on the entire GMOS instrument.
#  SIMULATION MODE VERSION.
#
#   It is assumed this script is being run from the "test" directory.
#
# Invocation:
#   gmosCheckoutSim level arg2 arg3 arg4
#      level = 1 (simple), 2 (thorough), 3 (full engineering checkout)
#      or 4 (maximum checkout).
#      arg2, arg3 and arg4 can be used to pass "-auto" and "-simulate"
#      arguments to the checkout scripts (except the engineering level scripts).
#      If "-noifu" is specified the non-IFU version of the mask checkout
#      script will be selected.
#
# Note:
#   This script runs all the checkout scripts sequentially. Many of these
#   scripts can, in fact, be run simultaneously. 
#

#
# Bail out if the scripts directory does not exist.
#
if ( !(-e scripts) ) then

   echo "Please cd to the 'test' directory before running this script." 
   exit
endif

#
# Obtain the level required. Default to 1 if not specified.
#

set level = $1

if ( $level == "" ) then

   set level = 1

else if ( $level < 0 || $level > 4 ) then

   echo "Invalid test level - must be one of the following:"
   echo "1 - simple test of each assembly"
   echo "2 - more thorough test of each assembly"
   echo "3 - engineering tests requiring interaction"
   echo "4 - additional engineering tests"
   exit
endif

echo " "
echo "GMOS instrument checkout at level " $level

#
# Extract other arguments
#

if ( "$2" == "-noifu" || "$3" == "-noifu" || "$4" == "-noifu" ) then
   echo "The mask assembly is assumed not to have an IFU."
   set noifu = 1
else
   echo "The mask assembly is assumed to have an IFU."
   set noifu = 0
endif

if ( "$2" == "-auto" || "$3" == "-auto" || "$4" == "-auto" ) then
   echo "Non-interactive scripts will be run in -auto mode."
   set auto = "-auto"
else
   set auto = ""
endif

if ( "$2" == "-simulate" || "$3" == "-simulate" || "$4" == "-simulate" ) then
   echo "All scripts will be run in -simulate mode."
   set simulate = "-simulate"
else
   set simulate = ""
endif

#
# Ensure the device reset aliases are set up
#

source ./setResetAliases

#
# State the assumptions and wait for a carriage return.
#
if ( -e gmosCheckout.asm ) then

   cat gmosCheckout.asm

   echo " "
   echo "(type <ret> when ready to proceed)"
   set dummy = $<
endif

#
# Start with all the interactive engineering level tests.
#

if ( $level > 2 ) then

#
# Engineering level tests of all the mask components
#

   echo " "
   echo "Mask Assembly Engineering Tests"
   echo " "
   echo "Please remove all the cassettes from the mask assembly."
   echo "(type <ret> when ready to proceed)"
   set dummy = $<

#
# Reset the mask assembly
#
   maskResetSim

#
# If required, run an additional engineering check the ensure the mask opto-sensors
# are working correctly.
#
   if ( $level > 3 ) then
      checkoutSim maskOptSensor $simulate
      echo " "
      echo "Please remove all the cassettes from the mask assembly."
      echo "(type <ret> when ready to proceed)"
      set dummy = $<
   endif

#
# Normal engineering checks on the gripper, release, extractor and cassette.
# These must all be done without any cassettes in place.
#
   gripResetSim
   checkoutSim grip $simulate

   releaseResetSim
   checkoutSim release $simulate

   extractorResetSim
   checkoutSim extractor $simulate

   cassetteResetSim
   checkoutSim cassette $simulate

   echo " "
   echo "Please replace all the cassettes in the mask assembly."
   echo "(type <ret> when ready to proceed)"
   set dummy = $<

#
# If required, run an additional engineering check the ensure all the cassette
# pins are working correctly. This check needs cassettes installed.
#
   if ( $level > 3 ) then
      checkoutSim cassettePin $simulate
   endif

#
# Engineering level tests of the grating turret and lifter
#

   echo " "
   echo "Grating Turret and Lifter Engineering Tests"
   echo " "
   echo "Please raise the grating lifter."
   echo "(type <ret> when ready to proceed)"
   set dummy = $<

   turretResetSim
   if ( $level > 3 ) then
      checkoutSim turretFull $simulate
   else
      checkoutSim turret $simulate
   endif

   echo " "
   echo "Please move the turret to position B and lower the lifter."
   echo "(type <ret> when ready to proceed)"
   set dummy = $<

   checkoutSim lifter $simulate

   echo " "
   echo "Interactive engineering tests finished."
   echo "Carrying on with other tests in $auto $simulate mode."
endif


#
# Check out the mask assembly, choosing the normal or NoIfu version of the
# script as appropriate. For a thorough check try putting every mask
# into the beam.
#

maskResetSim
if ( $noifu > 0 ) then
   checkoutSim maskNoIfu $auto $simulate
else
   checkoutSim mask $auto $simulate
endif

if ( $level > 1 ) then

   maskResetSim
   checkoutSim maskUpdate $auto $simulate
endif


#
# Check out the OIWFS assembly. For a thorough check run the ICD checkout
# script as well.
#

checkoutSim wfs $auto $simulate
if ( $level > 1 ) then
   checkoutSim wfsIcd $auto $simulate
endif


#
# Check out the filter assembly. For a thorough check exercise each
# filter wheel.
#

if ( $level > 1 ) then

   wheel1ResetSim
   checkoutSim wheel1 $auto $simulate

   wheel2ResetSim
   checkoutSim wheel2 $auto $simulate
endif

filterResetSim
checkoutSim filter $auto $simulate


#
# Check out the grating assembly. For a thorough check exercise all
# the grating tilts.
#

if ( $level > 1 ) then

   tiltAResetSim
   checkoutSim tiltA $auto $simulate

   tiltBResetSim
   checkoutSim tiltB $auto $simulate

   tiltCResetSim
   checkoutSim tiltC $auto $simulate

   tiltDResetSim
   checkoutSim tiltD $auto $simulate
endif

#
# Check the grating assembly. Include a calibration check at the maximum
# engineering level.
#

gratingResetSim
checkoutSim grating $auto $simulate

if ( $level > 3 ) then

   checkoutSim gratingCalib $auto $simulate
endif


#
# Check out the translation assembly. For a thorough check exercise all
# the axes.
#

if ( $level > 1 ) then

   xaxisResetSim
   checkoutSim xaxis $auto $simulate

   yaxisResetSim
   checkoutSim yaxis $auto $simulate

   zaxisResetSim
   checkoutSim zaxis $auto $simulate
endif

translationResetSim
checkoutSim translation $auto $simulate

echo " "
echo "+-------------------------------------------------------------------+"
echo "| GMOS instrument checkout completed.  Please check the log files,  |"
echo "| as some results may have scrolled off the screen.                 |"
echo "+-------------------------------------------------------------------+"
