#!/usr/local/bin/tcsh -f
#
#  This sets the environment variables and runs the tests
#
#
setenv DEFAULT_CONFIG_DIR ./configFiles

checkout cassetteErr $1 $2
checkout extractorErr $1 $2
#checkout gripErr $1 $2
#checkout releaseErr $1 $2
#checkout maskErr $1 $2

