# Include file identifying the target architecture (defines the T_A
# macro) and application configuration definitions

include ../.applTop
include $(APPLIC_TOP)/config/CONFIG

# External libraries on which this directory is dependent.
# DEPLIBS      =

# User compiler and loader flags
# SNC_FLAGS    =
# USR_CFLAGS   =
# USR_INCLUDES =
# USR_LDFLAGS  =
# USR_LDLIBS   =

# Add the record include (*.h) files to this variable.
# This causes the record *.h file to be built from the record *.dbd file.
RECTYPES =

# Add dbd files to this variable for installation.
DBDINSTALL =

# Add the source code files to this variable. The default has all .c files 
SRCS.c	= $(wildcard ../*.c) 

# Add the object files in one of these two variables. 
LIBOBJS +=

#OBJS	=  $(strip $(patsubst ../%.c,    %.o, $(SRCS.c))             \
		   $(patsubst ../%.st,   %.o, $(wildcard ../*.st  )) \
                   $(patsubst ../%.stpp, %.o, $(wildcard ../*.stpp)))

# Standard macros for files which are to be built and installed.
# PROD (products) and SCRIPTS are installed in INSTALL_BIN
PROD	= $(strip $(patsubst %.o, %, $(OBJS))                        \
		  $(patsubst ../%.vws, %, $(wildcard ../*.vws)))
SCRIPTS	=

# LIBNAME is installed in INSTALL_LIB
LIBNAME	=

# INC is installed in INSTALL_INCLUDE
INC	=

# MAN1 is installed in INSTALL_MAN/man1
MAN1	=

# DOCS are installed in INSTALL_DOC
DOCS	=

# DATA are installed in INSTALL_DATA
DATA  = ../ssrOn.pv
DATA += ../ssrOff.pv
DATA += ../gmosCc.pv
DATA += ../gmTranslationSim.pv
DATA += ../gmMaskSim.pv
DATA += ../gmLifterSim.pv
DATA += ../gmInterlockSim.pv
DATA += ../gmGratingSim.pv
DATA += ../gmFilterSim.pv
DATA += ../gmosCcSim.pv
DATA += ../gmSeqSim.pv
DATA += ../gmSeq.pv
DATA += ../gmLutSim.pv
DATA += ../gmOiwfsSim.pv
DATA += ../gmGrating.pv
DATA += ../gmFilter.pv
DATA += ../gmTranslation.pv
DATA += ../gmMask.pv
DATA += ../gmSeqTracking.pv
DATA += ../gmTempCalibrate.pv
DATA += ../gmOiwfs.pv

# Any extra targets can be placed in a TARGETS macro (the build target
# builds only pre_build, LIBNAME, TARGETS and PROD, not SCRIPTS, INC etc)
TARGETS	=

# Rules for building targets
include $(APPLIC_TOP)/config/RULES.Build

# There is no product rule, but one can be added and edited.
#$(PROD): $(OBJS)
#	$(RM) $@
#	$(LINK.c) $@ $(OBJS)
