#!/bin/csh -f
#
# Install script for Gemini GMOS system - extra commands to work around
# bug which makes adl2dm2.4 crash when building for the first time.
#

#
# Bug work around. Sometimes the adl2dl2.4 converter core dumps when
# attempting to build some of the dm screens. Building them a second time
# recovers the missing screens.
#

cd ./dl
touch *.adl
gmake
cd ..

exit 0
