#!/bin/sh -f
#
# Install script for Gemini GMOS system
#

host=`hostname`
if [ "`egrep $host /etc/hosts | egrep '^10\.'`" -ne "" ]; then
    site=MK;
else
    site=CP;
fi

slalib_dir=/gemini/GEM8.6/slalib/slalib
timelib_dir=/gemini/GEM8.6/timelib/timelib
astlib_dir=/gemini/GEM8.6/astlib/astlib

applSetup.pl -T ppc604_long -I adl -I alh -I capfast -I src -I startup -I db \
	     -d $astlib_dir -d $slalib_dir -d $timelib_dir -S $site $1 > $2 2>&1

gmake >> $2 2>&1

exit 0
