#!/bin/csh
#
# Start the GMOS detector controller alarm handler.
#
# Invocation:
#   ./gmosDcAlarm
#
# Original Author: Steven M Beard
#
# $Id$
#

setenv ALARMHANDLER ./data

set arg = "$1"
if "$arg" == "CP" then
   echo "Monitoring alarms in GMOS DC Cerro Pachon database"
   alh -l ./data -a GMOSDC-CP.alhAlarm -f ./data GMOSDC-CP.alhConfig &
else if "$arg" == "RS" then
   echo "Monitoring alarms in GMOS DC Mauna Kea database"
   alh -l ./data -a GMOSDC-MKRR.alhAlarm -f ./data GMOSDC-MKRR.alhConfig &
else if "$arg" == "PRE" then
   echo "Monitoring alarms in GMOS DC Mauna Kea database"
   alh -l ./data -a GMOSDC-MKRR.alhAlarm -f ./data GMOSDC-MKRR.alhConfig &
else if "$arg" == "SR" then
   echo "Monitoring alarms in GMOS DC Mauna Kea database"
   alh -l ./data -a GMOSDC-MKRR.alhAlarm -f ./data GMOSDC-MKRR.alhConfig &
else if "$arg" == "POST" then
   echo "Monitoring alarms in GMOS DC Mauna Kea database"
   alh -l ./data -a GMOSDC-MKRR.alhAlarm -f ./data GMOSDC-MKRR.alhConfig &
else if "$arg" == "SS" then
   echo "Monitoring alarms in GMOS DC Mauna Kea database - simulated"
   alh -l ./data -a GMOSDC-MKSS.alhAlarm -f ./data GMOSDC-MKSS.alhConfig &
else if "$arg" == "SIM" then
   echo "Monitoring alarms in GMOS DC Mauna Kea database - simulated"
   alh -l ./data -a GMOSDC-MKSS.alhAlarm -f ./data GMOSDC-MKSS.alhConfig &
else
   echo "Monitoring alarms in GMOS DC Mauna Kea database"
   alh -l ./data -a GMOSDC-MKRR.alhAlarm -f ./data GMOSDC-MKRR.alhConfig &
endif

echo "NOTE - Not all workstations support audible alarms"

