#!/bin/csh
#
# Start all the GMOS MK display screens
#
# Invocation:
#   gmosStartMK [option] [option] [sim]
#
#   option=noconsole means "do not start the VxWorks consoles"
#   option=nolog     means "do not log output from the VxWorks consoles"
#   sim=SIM          means "connect to simulation version of software"
#
# Original Author: Steven M Beard
#

#
# Look for the strings "nolog" and "noconsole" in the arguments.
#

set options="$1 $2 $3"

if ( `echo $options | grep -i nolog | wc -l` == 1 ) then
   set nolog = nolog
else
   set nolog = ""
endif

if ( `echo $options | grep -i noconsole | wc -l` == 1 ) then
   set noconsole = 1
else
   set noconsole = 0
endif
    echo 'Type "source .login" and try again.'

#
# Extract the optional simulation mode from the last argument specified, which
# can be the 2nd or 3rd depending on whether one or both options are specified.
#

if ( $3 != "" ) then
   set sim = "$3"
else
   set sim = "$2"
endif

#
# Check that all the necessary environment variables are defined.
#

if (!($?EPICS)) then
    echo ""
    echo "EPICS environment not defined."
    echo ""
    echo 'Type "source .cshrc" and try again.'
    exit
endif

if (!($?GMOS_OP)) then
    echo ""
    echo "Location of GMOS operational software not defined."
    echo ""
    echo 'Type "source gmosCshrc" and try again.'
    exit
endif

#
# Only allow access to the MK hardware if the GMOS_MK_ACCESS environment
# variable has been defined.
#

if (!($?GMOS_MK_ACCESS)) then
    echo ""
    echo "GMOS MK safety check failed."
    echo ""
    echo "Before starting the GMOS software, which will allow control of real"
    echo 'hardware, you must type "gmosMK" to confirm that it is safe to do so.'
    echo ""
    exit
else
    echo ""
    echo "GMOS MK safety check passed."
endif

if (!($?DISPLAY)) then
    echo ""
    echo "No DISPLAY variable defined."
    echo ""
    echo 'Type "setenv DISPLAY whatever" and try again.'
    exit
else
    echo "Display screens will go to ${DISPLAY}"
endif

#
# Check the software directory
#

echo ""
echo "Using the GMOS software in ${GMOS_OP}."

#
# Check that the software has been built and a pointer to the detector controller exists
#

if (!(-e ${GMOS_OP}/bin)) then
    echo ""
    echo "Software not built properly - no bin directory found."
    echo ""
    exit
endif

if (!(-e ${GMOS_OP}/data)) then
    echo ""
    echo "Software not built properly - no data directory found."
    echo ""
    exit
endif

#
# The software is set up correctly. Start up the VxWorks console windows,
# assuming these two commands are in the PATH.
#

if ( $noconsole == 1 ) then

    echo "No VxWorks consoles will be started."
else

    echo ""
    echo "Starting GMOS components controller VxWorks console window."
    gmoscc $nolog

    echo ""
    echo "Starting GMOS detector controller VxWorks console window."
    gmosdc $nolog
endif

#
# Finally, start the dm screens `, assuming this command is in the PATH
# (argument $sim is used for testing)
#
gmosStart $sim




