#!/bin/csh
#
# Start the GMOS components controller alarm handler.
#
# Invocation:
#   ./gmosCcAlarm
#
# Original Author: Steven M Beard
#
# $Id$
#

setenv ALARMHANDLER ${GMOS_OP}/data

set arg = "$1"
if "$arg" == "CP" then
   echo "Monitoring alarms in GMOS Cerro Pachon database"
   alh -l ${GMOS_OP}/data -a GMOS-CP.alhAlarm -f ${GMOS_OP}/data GMOS-CP.alhConfig &
else if "$arg" == "RS" then
   echo "Monitoring alarms in GMOS Mauna Kea database - simulated post focal-plane"
   alh -l ${GMOS_OP}/data -a GMOS-MKRS.alhAlarm -f ${GMOS_OP}/data GMOS-MKRS.alhConfig &
else if "$arg" == "PRE" then
   echo "Monitoring alarms in GMOS Mauna Kea database - simulated post focal-plane"
   alh -l ${GMOS_OP}/data -a GMOS-MKRS.alhAlarm -f ${GMOS_OP}/data GMOS-MKRS.alhConfig &
else if "$arg" == "SR" then
   echo "Monitoring alarms in GMOS Mauna Kea database - simulated pre focal-plane"
   alh -l ${GMOS_OP}/data -a GMOS-MKSR.alhAlarm -f ${GMOS_OP}/data GMOS-MKSR.alhConfig &
else if "$arg" == "POST" then
   echo "Monitoring alarms in GMOS Mauna Kea database - simulated pre focal-plane"
   alh -l ${GMOS_OP}/data -a GMOS-MKSR.alhAlarm -f ${GMOS_OP}/data GMOS-MKSR.alhConfig &
else if "$arg" == "SS" then
   echo "Monitoring alarms in GMOS Mauna Kea database - simulated"
   alh -l ${GMOS_OP}/data -a GMOS-MKSS.alhAlarm -f ${GMOS_OP}/data GMOS-MKSS.alhConfig &
else if "$arg" == "SIM" then
   echo "Monitoring alarms in GMOS Mauna Kea database - simulated"
   alh -l ${GMOS_OP}/data -a GMOS-MKSS.alhAlarm -f ${GMOS_OP}/data GMOS-MKSS.alhConfig &
else
   echo "Monitoring alarms in GMOS Mauna Kea database"
   alh -l ${GMOS_OP}/data -a GMOS-MKRR.alhAlarm -f ${GMOS_OP}/data GMOS-MKRR.alhConfig &
endif

echo "NOTE - Not all workstations support audible alarms"

