#!/bin/csh -f
#
# Script to spawn an xterm to connect to any VME crate through the annex,
# allowing the annex to prompt for a port number.
#
# A log file is written to the "${HOME}/consoleLogs" directory.
# The log file output may be suppressed by specifying "nolog" as a first
# argument.
#

#
# Save the current day
#

set day = `date +%d%h%y`

#
# Create the "consoleLogs" directory if it doesn't exist.
#

if ( !(-e ${HOME}/consoleLogs) ) then

    mkdir ${HOME}/consoleLogs
endif

if (!(-e ${HOME}/consoleLogs/$day)) then

    mkdir ${HOME}/consoleLogs/$day
endif

#
# Change directory to day's console log directory.
#

pushd ${HOME}/consoleLogs/$day

#
# Spawn an X terminal to act as the VxWorks console.
#

if ( $1 == "nolog" ) then

   xterm -geometry 80x50-0+0 -sb -sl 256 -n IOC -T "VxWorks Console" -e gmosIocAnnex 10.1.5.66 &
   echo "No log file will be created."
else

   xterm -l -geometry 80x50-0+0 -sb -sl 256 -n IOC -T "VxWorks Console" -e gmosIocAnnex 10.1.5.66 &
   echo "A log file will be created in the `pwd`"
   echo "directory. Check for files called XtermLog.*"
endif

#
# Restore the original directory.
#

popd
