
include Target.include
include .applTop/config/CONFIG
ADL2DL = $(EPICS)/extensions/bin/solaris/adl2dl2.4

SCRIPTS = gmosCcStartMKRR gmosCcStartMKRS gmosCcStartMKSR gmosCcStartMKSS \
	  gmosCcStartCP gmEditFile gmEditFileField gmCcDoCommand \
	  gmSeqStart gmSeqStartMKRR gmSeqDoCommand gmSeqCcCommand \
          gmosStartMKRR gmosStartMKSS gmosStartMKSS2 gmosStartCP

# List of display (*.dl) files
DATA    = colors.dl gmColors.dl $(wildcard ../*.dl) \
          $(patsubst ../%.adl, %.dl, $(wildcard ../*.adl ../*.bit ../*.tk ../*.sh ../*.test))

include .applTop/config/RULES.Build
