#!/usr/local/bin/tcsh -f
#
# logImages
#
# Description:
#
#   A simple script to log images to file at a periodic interval
#
#   It is assumed this script is being run from the "test" directory.
#   The detector controller must already have been initalised
#   and set into the desired configuration.
#
# Invocation:
#   logImages interval
#
# NOTE:
#   This script is designed to be as simple as possible, so it does not do as much
#   checking as a dhsTestCmdr script. It is designed to generate test data rather
#   than to check out the correct operation of the instrument.
#

set jiggleOffset  = 10.0

#
# Check for arguments
#

if ($#argv != 2) then
    echo "Please supply interval between observations (in minutes)"
    echo "then the number of iterations to perform."
    exit
endif

#
# Get the current day and calculate interval
#

set day = `date +%d%h%y`

set intervalSeconds = `mult $1 60`

if ($intervalSeconds <= 0) then
    echo "Interval must be greater than zero"
    exit
endif

#
# Only allow access to the MK hardware if the GMOS_MK_ACCESS environment
# variable has been defined.
#

if (!($?GMOS_MK_ACCESS)) then
    echo ""
    echo "GMOS MK safety check failed."
    echo ""
    echo "Before executing this script, which will move real MK hardware,"
    echo 'you must type "gmosMK" to confirm that it is safe to do so.'
    echo ""
    exit
else
    echo ""
    echo "GMOS MK safety check passed."
    echo ""
endif

#
# Bail out if the scripts directory does not exist.
#

if ( !(-e scripts) ) then

   echo "Please cd to the 'test' directory before running this script." 
   exit
endif

#
# Create the log directory if need be...
#

if (!(-e logfiles/${day})) then
    mkdir logfiles/${day}
    echo "Creating directory ./logfiles/"${day}
    sleep 1
endif

echo "Fitssaver files can be moved to ./logfiles/"${day}" if you wish"
sleep 1

if (!(-e logfiles/${day}/gratingRepeatLog)) then
    echo "Creating image log file ./logfile/"${day}"/gratingRepeatLog"
    echo "Day Month Date Time Year Filename temp0 temp1 temp2 temp3 temp4 temp5 temp6 temp7 temp8 detTemp Comment" | cat >> ./logfiles/${day}/gratingRepeatLog
    sleep 1
endif

echo "Image file information will be stored in ./logfiles/"${day}"/gratingRepeatLog"
sleep 1

echo ""
echo "It is assumed you have already configured the detector controller,"
echo "and that the grating assembly is initialised, indexed and updated."
echo ""
echo "Type Ctrl-c when you want to finish the script."
echo "(type <ret> when ready to proceed)"
set dummy = $<

echo ""
date
echo ""
echo "Please log the following information:"
echo ""
echo "1. Date/Time"
echo "2. Software/Model version"
echo "3. CCD exposure time"
echo "4. Mask Id"
echo "5. Grating Id"
echo "6. Grating angle"
echo "7. Anything else you want to"
echo ""
echo "(type <ret> when ready to proceed)"
set dummy = $<

echo "Please enter a file number"
echo "The first filename will be gXXXXX"
set filenumber = $<

@ filenumber -= 1
@ filenumber += 1

echo "" | cat >> ./logfiles/${day}/gratingRepeatLog    

set gratingID = `caget "gm:cc:grAssembly.B" | sed 's|gm:cc:grAssembly.B||g'`
echo "Current grating ID is "$gratingID

echo ""
echo "Please input the grating ID (barcode number) you wish to image with..."
set imageGratingID = $<
echo "Script will image using grating ID "$imageGratingID

echo ""
echo "Please input the grating ID (barcode number) you wish to move to (and back from)..."
set moveGratingID = $<
echo "Script will move to grating ID "$moveGratingID" between images"

echo ""
set imagingAngle = `caget "gm:cc:grAssembly.C" | sed 's|gm:cc:grAssembly.C||g'`
echo "Current grating angle is "$imagingAngle

#set jiggleAngle = `add $imagingAngle -$jiggleOffset`
set jiggleAngle = 5
echo "Grating will jiggle to "$jiggleAngle

set nonContactAngle = `add $imagingAngle +0.037`
#set nonContactAngle = 65.037
echo "Grating will jiggle in Non-Contact mode, to "$nonContactAngle

#
# Start the observations.
#

    #
    # Start position for the grating
    #

    echo "Moving to the start configuration for the grating assembly."
    echo "Moving..."

    set moveResponse = `moveAssembly gm:cc:grAssembly 0 ${imageGratingID} ${imagingAngle}`
    set moveStatus = `echo $moveResponse | grep 'Command Success'`
    if ( $#moveStatus != 2 ) then
	echo "Grating assembly move 1 failed"
	caget gm:cc:grAssembly.MESS
	exit -1
    endif
    echo "Grating assembly move 1 succeeded"


    set observeTime = `date +"%a %b %d %T %Y"`
    echo ""
    echo "*"
    echo "* The time now is ${observeTime}"
    echo "*"
    echo ""

    set observeTime = `date +"%a %b %d %T %Y"`

    echo "Measuring temperatures at ${observeTime}"

    set temp0 = `caget "gm:cc:temp0.VAL" | sed 's|gm:cc:temp0.VAL||g'`
    echo "temp0 is "$temp0
    set temp1 = `caget "gm:cc:temp1.VAL" | sed 's|gm:cc:temp1.VAL||g'`
    echo "temp1 is "$temp1
    set temp2 = `caget "gm:cc:temp2.VAL" | sed 's|gm:cc:temp2.VAL||g'`
    echo "temp2 is "$temp2
    set temp3 = `caget "gm:cc:temp3.VAL" | sed 's|gm:cc:temp3.VAL||g'`
    echo "temp3 is "$temp3
    set temp4 = `caget "gm:cc:temp4.VAL" | sed 's|gm:cc:temp4.VAL||g'`
    echo "temp4 is "$temp4
    set temp5 = `caget "gm:cc:temp5.VAL" | sed 's|gm:cc:temp5.VAL||g'`
    echo "temp5 is "$temp5
    set temp6 = `caget "gm:cc:temp6.VAL" | sed 's|gm:cc:temp6.VAL||g'`
    echo "temp6 is "$temp6
    set temp7 = `caget "gm:cc:temp7.VAL" | sed 's|gm:cc:temp7.VAL||g'`
    echo "temp7 is "$temp7
    set temp8 = `caget "gm:cc:temp8.VAL" | sed 's|gm:cc:temp8.VAL||g'`
    echo "temp8 is "$temp8
    set detTemp = `caget "gm:sad:dc:detTemp.VAL" | sed 's|gm:sad:dc:detTemp.VAL||g'`
    echo "detector temp is "$detTemp

    echo "Saving data to g${filenumber}"

    #
    # Set the file name to the current time.
    #

    set fileResponse = `setObserveFilename gm: g${filenumber}`
    set fileStatus = `echo $fileResponse | grep 'Command Success'`
    if ( $#fileStatus != 2 ) then
	echo "Setting filename failed at "${observeTime}
	exit -1
    endif

    #
    # Make an observation
    #

    echo "Observing"
    set observeResponse = `executeObserve gm:`
    set observeStatus = `echo $observeResponse | grep 'Command Success'`
    if ( $#observeStatus != 2 ) then
	echo "Observation failed at "${observeTime}
	exit -1
    endif

    #
    # Log the filename, time, temps etc.
    #

    set comment = "Initial image"

    echo ${observeTime} g${filenumber} $temp0 $temp1 $temp2 $temp3 $temp4 $temp5 $temp6 $temp7 $temp8 $detTemp $comment | cat >> ./logfiles/${day}/gratingRepeatLog    

    @ filenumber += 1


    set repetitions = $2
    set repsDone    = 0

    while ($repsDone < $repetitions)

	@ repsDone += 1
	echo ""
	echo "Repetition "$repsDone

	#
	# Flush the lifter pneumatics
	#

	# echo "Exhausting the lifter air pressure"
	# lifterExhaust gm:

	#
	# Jiggle the grating
	#

	echo "Jiggling the grating to remove residual stresses."
	echo "Tilt away..."

# insert the command to set the backlash correction to default (150 in V12) for all tilt devices

	set blcoA = `caget "gm:cc:grADevice.BLCO" | sed 's|gm:cc:grADevice.BLCO||g'`
	set blcoB = `caget "gm:cc:grBDevice.BLCO" | sed 's|gm:cc:grBDevice.BLCO||g'`
	set blcoC = `caget "gm:cc:grCDevice.BLCO" | sed 's|gm:cc:grCDevice.BLCO||g'`
	set blcoD = `caget "gm:cc:grDDevice.BLCO" | sed 's|gm:cc:grDDevice.BLCO||g'`

	caput gm:cc:grADevice.BLCO 150.0
	caput gm:cc:grBDevice.BLCO 150.0
	caput gm:cc:grCDevice.BLCO 150.0
	caput gm:cc:grDDevice.BLCO 150.0

	set moveResponse = `moveAssembly gm:cc:grAssembly 0 ${imageGratingID} ${jiggleAngle}`
	set moveStatus = `echo $moveResponse | grep 'Command Success'`
	if ( $#moveStatus != 2 ) then
	    echo "Grating assembly move 1 failed"
	    caget gm:cc:grAssembly.MESS
	    exit -1
	endif
	echo "Grating assembly move 1 succeeded"


	echo "Tilt back..."
	set moveResponse = `moveAssembly gm:cc:grAssembly 0 ${imageGratingID} ${imagingAngle}`
	set moveStatus = `echo $moveResponse | grep 'Command Success'`
	if ( $#moveStatus != 2 ) then
	    echo "Grating assembly move 2 failed"
	    caget gm:cc:grAssembly.MESS
	    exit -1
	endif
	echo "Grating assembly move 2 succeeded"

	echo "Tilt to remove contact with worm..."

# insert the command to set the backlash correction to 0 (in tilt devices "more status" screen)

#	set blcoA = `caget "gm:cc:grADevice.BLCO" | sed 's|gm:cc:grADevice.BLCO||g'`
#	set blcoB = `caget "gm:cc:grBDevice.BLCO" | sed 's|gm:cc:grBDevice.BLCO||g'`
#	set blcoC = `caget "gm:cc:grCDevice.BLCO" | sed 's|gm:cc:grCDevice.BLCO||g'`
#	set blcoD = `caget "gm:cc:grDDevice.BLCO" | sed 's|gm:cc:grDDevice.BLCO||g'`

	caput gm:cc:grADevice.BLCO 0.0
	caput gm:cc:grBDevice.BLCO 0.0
	caput gm:cc:grCDevice.BLCO 0.0
	caput gm:cc:grDDevice.BLCO 0.0

	set moveResponse = `moveAssembly gm:cc:grAssembly 0 ${imageGratingID} ${nonContactAngle}`
	set moveStatus = `echo $moveResponse | grep 'Command Success'`
	if ( $#moveStatus != 2 ) then
	    echo "Grating assembly move 1 failed"
	    caget gm:cc:grAssembly.MESS
	    exit -1
	endif
	echo "Grating assembly move 3 succeeded"


	set observeTime = `date +"%a %b %d %T %Y"`

	echo "Measuring temperatures at ${observeTime}"

	set temp0 = `caget "gm:cc:temp0.VAL" | sed 's|gm:cc:temp0.VAL||g'`
	echo "temp0 is "$temp0
	set temp1 = `caget "gm:cc:temp1.VAL" | sed 's|gm:cc:temp1.VAL||g'`
	echo "temp1 is "$temp1
	set temp2 = `caget "gm:cc:temp2.VAL" | sed 's|gm:cc:temp2.VAL||g'`
	echo "temp2 is "$temp2
	set temp3 = `caget "gm:cc:temp3.VAL" | sed 's|gm:cc:temp3.VAL||g'`
	echo "temp3 is "$temp3
	set temp4 = `caget "gm:cc:temp4.VAL" | sed 's|gm:cc:temp4.VAL||g'`
	echo "temp4 is "$temp4
	set temp5 = `caget "gm:cc:temp5.VAL" | sed 's|gm:cc:temp5.VAL||g'`
	echo "temp5 is "$temp5
	set temp6 = `caget "gm:cc:temp6.VAL" | sed 's|gm:cc:temp6.VAL||g'`
	echo "temp6 is "$temp6
	set temp7 = `caget "gm:cc:temp7.VAL" | sed 's|gm:cc:temp7.VAL||g'`
	echo "temp7 is "$temp7
	set temp8 = `caget "gm:cc:temp8.VAL" | sed 's|gm:cc:temp8.VAL||g'`
	echo "temp8 is "$temp8
	set detTemp = `caget "gm:sad:dc:detTemp.VAL" | sed 's|gm:sad:dc:detTemp.VAL||g'`
	echo "detector temp is "$detTemp

	echo "Saving data to g${filenumber}"

	#
	# Set the file name to the current time.
	#

	set fileResponse = `setObserveFilename gm: g${filenumber}`
	set fileStatus = `echo $fileResponse | grep 'Command Success'`
	if ( $#fileStatus != 2 ) then
	    echo "Setting filename failed at "${observeTime}
	    exit -1
	endif

	#
	# Make an observation
	#

	echo "Observing"
	set observeResponse = `executeObserve gm:`
	set observeStatus = `echo $observeResponse | grep 'Command Success'`
	if ( $#observeStatus != 2 ) then
	    echo "Observation failed at "${observeTime}
	    exit -1
	endif

	#
	# Log the filename, time, temps etc.
	#

	set comment = "Image after jiggle"

	echo ${observeTime} g${filenumber} $temp0 $temp1 $temp2 $temp3 $temp4 $temp5 $temp6 $temp7 $temp8 $detTemp $comment | cat >> ./logfiles/${day}/gratingRepeatLog

	@ filenumber += 1
    
	#
	# Change the in-beam grating
	#

	echo "Changing the in-beam grating to remove residual stresses."
	echo "Move away..."

	set moveResponse = `moveAssembly gm:cc:grAssembly 1 ${moveGratingID} ${nonContactAngle}`
	set moveStatus = `echo $moveResponse | grep 'Command Success'`
	if ( $#moveStatus != 2 ) then
	    echo "Grating assembly move 1 failed"
	    caget gm:cc:grAssembly.MESS
	    exit -1
	endif
	echo "Grating assembly move 1 succeeded"


	echo "Move back..."
	set moveResponse = `moveAssembly gm:cc:grAssembly 1 ${imageGratingID} ${nonContactAngle}`
	set moveStatus = `echo $moveResponse | grep 'Command Success'`
	if ( $#moveStatus != 2 ) then
	    echo "Grating assembly move 2 failed"
	    caget gm:cc:grAssembly.MESS
	    exit -1
	endif
	echo "Grating assembly move 2 succeeded"

	set observeTime = `date +"%a %b %d %T %Y"`

	echo "Measuring temperatures at ${observeTime}"

	set temp0 = `caget "gm:cc:temp0.VAL" | sed 's|gm:cc:temp0.VAL||g'`
	echo "temp0 is "$temp0
	set temp1 = `caget "gm:cc:temp1.VAL" | sed 's|gm:cc:temp1.VAL||g'`
	echo "temp1 is "$temp1
	set temp2 = `caget "gm:cc:temp2.VAL" | sed 's|gm:cc:temp2.VAL||g'`
	echo "temp2 is "$temp2
	set temp3 = `caget "gm:cc:temp3.VAL" | sed 's|gm:cc:temp3.VAL||g'`
	echo "temp3 is "$temp3
	set temp4 = `caget "gm:cc:temp4.VAL" | sed 's|gm:cc:temp4.VAL||g'`
	echo "temp4 is "$temp4
	set temp5 = `caget "gm:cc:temp5.VAL" | sed 's|gm:cc:temp5.VAL||g'`
	echo "temp5 is "$temp5
	set temp6 = `caget "gm:cc:temp6.VAL" | sed 's|gm:cc:temp6.VAL||g'`
	echo "temp6 is "$temp6
	set temp7 = `caget "gm:cc:temp7.VAL" | sed 's|gm:cc:temp7.VAL||g'`
	echo "temp7 is "$temp7
	set temp8 = `caget "gm:cc:temp8.VAL" | sed 's|gm:cc:temp8.VAL||g'`
	echo "temp8 is "$temp8
	set detTemp = `caget "gm:sad:dc:detTemp.VAL" | sed 's|gm:sad:dc:detTemp.VAL||g'`
	echo "detector temp is "$detTemp

	echo "Saving data to g${filenumber}"

	#
	# Set the file name to the current time.
	#

	set fileResponse = `setObserveFilename gm: g${filenumber}`
	set fileStatus = `echo $fileResponse | grep 'Command Success'`
	if ( $#fileStatus != 2 ) then
	    echo "Setting filename failed at "${observeTime}
	    exit -1
	endif

	#
	# Make an observation
	#

	echo "Observing"
	set observeResponse = `executeObserve gm:`
	set observeStatus = `echo $observeResponse | grep 'Command Success'`
	if ( $#observeStatus != 2 ) then
	    echo "Observation failed at "${observeTime}
	    exit -1
	endif

	#
	# Log the filename, time, temps etc.
	#

	set comment = "Image after turret move"

	echo ${observeTime} g${filenumber} $temp0 $temp1 $temp2 $temp3 $temp4 $temp5 $temp6 $temp7 $temp8 $detTemp $comment | cat >> ./logfiles/${day}/gratingRepeatLog

	@ filenumber += 1

	echo ""
	echo "The time is now "`date +"%T"`

	if ($repsDone < $repetitions) then
	    echo "Type Ctrl-c to stop the script."
	    echo "Waiting for ${intervalSeconds} seconds..."
	    sleep $intervalSeconds
	endif
    end

    #
    # Restore  the grating
    #

    echo "Restoring the configuration for the grating assembly."
    echo "Moving..."

# insert command to put backlash correction back to 150.0

    caput gm:cc:grADevice.BLCO 150.0
    caput gm:cc:grBDevice.BLCO 150.0
    caput gm:cc:grCDevice.BLCO 150.0
    caput gm:cc:grDDevice.BLCO 150.0

    # caput gm:cc:grADevice.BLCO blcoA
    # caput gm:cc:grBDevice.BLCO blcoB
    # caput gm:cc:grCDevice.BLCO blcoC
    # caput gm:cc:grDDevice.BLCO blcoD

    set moveResponse = `moveAssembly gm:cc:grAssembly 0 ${imageGratingID} ${imagingAngle}`
    set moveStatus = `echo $moveResponse | grep 'Command Success'`
    if ( $#moveStatus != 2 ) then
	echo "Grating assembly move 1 failed"
	caget gm:cc:grAssembly.MESS
	exit -1
    endif
    echo "Grating assembly move 1 succeeded"


exit
