#!/usr/local/bin/tcsh -f
#
# logImages
#
# Description:
#
#   A simple script to log images to file at a periodic interval
#
#   It is assumed this script is being run from the "test" directory.
#   The detector controller must already have been initalised
#   and set into the desired configuration.
#
# Invocation:
#   logImages interval
#
# NOTE:
#   This script is designed to be as simple as possible, so it does not do as much
#   checking as a dhsTestCmdr script. It is designed to generate test data rather
#   than to check out the correct operation of the instrument.
#

# Set some numbers - suitable filter barcode IDs

set filter1_pos1 = 176
set filter1_pos2 = 175
set filter1_pos3 = 38
set filter2_pos  = 35
set jiggleOffset = 10.0

#
# Check for arguments
#

if ($#argv != 2) then
    echo "Please supply interval between observations (in minutes)"
    echo "then the number of clear mask samples to take per iteration."
    exit
endif

#
# Get the current day and calculate interval
#

set day = `date +%d%h%y`

set intervalSeconds = `mult $1 60`

if ($intervalSeconds <= 0) then
    echo "Interval must be greater than zero"
    exit
endif

#
# Only allow access to the MK hardware if the GMOS_MK_ACCESS environment
# variable has been defined.
#

#if (!($?GMOS_MK_ACCESS)) then
#    echo ""
#    echo "GMOS MK safety check failed."
#    echo ""
#    echo "Before executing this script, which will move real MK hardware,"
#    echo 'you must type "gmosMK" to confirm that it is safe to do so.'
#    echo ""
#    exit
#else
#    echo ""
#     echo "GMOS MK safety check passed."
#    echo ""
#endif

echo "Simulation mode - no safety check required"

#
# Bail out if the scripts directory does not exist.
#

if ( !(-e scripts) ) then

   echo "Please cd to the 'test' directory before running this script." 
   exit
endif

#
# Create the log directory if need be...
#

if (!(-e logfiles/${day})) then
    mkdir logfiles/${day}
    echo "Creating directory ./logfiles/"${day}
    sleep 1
endif

echo "Fitssaver files can be moved to ./logfiles/"${day}" if you wish"
sleep 1

if (!(-e logfiles/${day}/imageLog)) then
    echo "Creating image log file ./logfile/"${day}"/imageLog"
    echo "Day Month Date Time Year Filename Filter1Id Filter2Id temp0 temp1 temp2 temp3 temp4 temp5 temp6 temp7 temp8 detTemp deltaX(x-talk) deltaY(x-talk) deltaX(thermal) deltaY(thermal) deltaZ(thermal) X Y Z resetTemp offsetTemp filteredTemp" | cat >> ./logfiles/${day}/imageLog
    sleep 1
endif

echo "Image file information will be stored in ./logfiles/"${day}"/imageLog"
sleep 1

echo ""
echo "It is assumed you have already configured the detector controller,"
echo "and executed INIT, INDEX and UPDATE on the filter wheel assembly."
echo "You must also INIT, INDEX and position the translation assembly,"
echo "and ensure that the demand (input) positions are correct."
echo ""
echo "Type Ctrl-c when you want to finish the script."
echo "(type <ret> when ready to proceed)"
set dummy = $<

echo ""
date
echo ""
echo "Please log the following information:"
echo ""
echo "1. Date/Time"
echo "2. Software/Model version"
echo "3. CCD exposure time"
echo "4. Mask Id"
echo "5. Grating Id"
echo "6. Grating angle"
echo ""
echo "(type <ret> when ready to proceed)"
set dummy = $<

echo "Please enter a file number"
echo "The first filename will be gXXXXX"
set filenumber = $<

@ filenumber -= 1
@ filenumber += 1

echo "" | cat >> ./logfiles/${day}/imageLog    

set gratingID = `caget "g7:cc:grAssembly.B" | sed 's|g7:cc:grAssembly.B||g'`
echo "Current grating ID is "$gratingID

set imagingAngle = `caget "g7:cc:grAssembly.C" | sed 's|g7:cc:grAssembly.C||g'`
echo "Current grating angle is "$imagingAngle

set jiggleAngle = `add $imagingAngle -$jiggleOffset`
echo "Grating will jiggle to "$jiggleAngle

#
# Start the observations.
#

while ( 1 )

    set observeTime = `date +"%a %b %d %T %Y"`
    echo ""
    echo "*"
    echo "* The time now is ${observeTime}"
    echo "*"
    echo ""

    #
    # Flush the lifter pneumatics
    #

    lifterExhaust g7:
    echo "Exhausting the lifter air pressure"

    #
    # Move to the first filter wheel position.
    #

    echo "Moving to first filter wheel position..."
    set moveResponse = `moveAssembly g7:cc:fltAssembly $filter1_pos1 $filter2_pos`
    set moveStatus = `echo $moveResponse | grep 'Command Success'`
    if ( $#moveStatus != 2 ) then
	echo "Filter move failed"
	caget g7:cc:fltAssembly.MESS
	exit -1
    endif
    echo "Filter move succeeded"

    echo "Dummy move of translation assembly..."

    # We need to get one of the input parameters to feed back (MARK the record)

    set dtaA = `caget "g7:cc:dtaAssembly.A" | sed 's|g7:cc:dtaAssembly.A||g'`

    set moveResponse = `moveAssembly g7:cc:dtaAssembly ${dtaA}`
    set moveStatus = `echo $moveResponse | grep 'Command Success'`
    if ( $#moveStatus != 2 ) then
	echo "Assembly move failed"
	caget g7:cc:dtaAssembly.MESS
	exit -1
    endif
    echo "Translation stage move succeeded"

    set observeTime = `date +"%a %b %d %T %Y"`

    echo "Measuring temperatures at ${observeTime}"

    set temp0 = `caget "g7:cc:temp0.VAL" | sed 's|g7:cc:temp0.VAL||g'`
    echo "temp0 is "$temp0
    set temp1 = `caget "g7:cc:temp1.VAL" | sed 's|g7:cc:temp1.VAL||g'`
    echo "temp1 is "$temp1
    set temp2 = `caget "g7:cc:temp2.VAL" | sed 's|g7:cc:temp2.VAL||g'`
    echo "temp2 is "$temp2
    set temp3 = `caget "g7:cc:temp3.VAL" | sed 's|g7:cc:temp3.VAL||g'`
    echo "temp3 is "$temp3
    set temp4 = `caget "g7:cc:temp4.VAL" | sed 's|g7:cc:temp4.VAL||g'`
    echo "temp4 is "$temp4
    set temp5 = `caget "g7:cc:temp5.VAL" | sed 's|g7:cc:temp5.VAL||g'`
    echo "temp5 is "$temp5
    set temp6 = `caget "g7:cc:temp6.VAL" | sed 's|g7:cc:temp6.VAL||g'`
    echo "temp6 is "$temp6
    set temp7 = `caget "g7:cc:temp7.VAL" | sed 's|g7:cc:temp7.VAL||g'`
    echo "temp7 is "$temp7
    set temp8 = `caget "g7:cc:temp8.VAL" | sed 's|g7:cc:temp8.VAL||g'`
    echo "temp8 is "$temp8
    set detTemp = `caget "g7:sad:dc:detTemp.VAL" | sed 's|g7:sad:dc:detTemp.VAL||g'`
    echo "detector temp is "$detTemp
    set thermalX = `caget "g7:cc:dtaAssembly.VALA" | sed 's|g7:cc:dtaAssembly.VALA||g'`
    echo "Calculated thermal X offset is "$thermalX
    set thermalY = `caget "g7:cc:dtaAssembly.VALB" | sed 's|g7:cc:dtaAssembly.VALB||g'`
    echo "Calculated thermal Y offset is "$thermalY
    set thermalZ = `caget "g7:cc:dtaAssembly.VALC" | sed 's|g7:cc:dtaAssembly.VALC||g'`
    echo "Calculated thermal Z offset is "$thermalZ
    set   resetTemp = `caget "g7:cc:dtaresetTemp.VAL" | sed 's|g7:cc:dtaresetTemp.VAL||g'`
    echo "Zero thermal offset temp is "$resetTemp
    set   offsetTemp = `caget "g7:cc:dtaoffsetTemp.VAL" | sed 's|g7:cc:dtaoffsetTemp.VAL||g'`
    echo "Thermal offset temp is "$offsetTemp
    set   filteredTemp = `caget "g7:cc:dtafilteredTemp.VAL" | sed 's|g7:cc:dtafilteredTemp.VAL||g'`
    echo "Thermal offset temp (filtered) is "$filteredTemp
    set   crosstalkX = `caget "g7:cc:dtacrossx.VAL" | sed 's|g7:cc:dtacrossx.VAL||g'`
    echo "Calculated x-talk X offset is "$crosstalkX
    set   crosstalkY = `caget "g7:cc:dtacrossy.VAL" | sed 's|g7:cc:dtacrossy.VAL||g'`
    echo "Calculated x-talk Y offset is "$crosstalkY
    set transX = `caget "g7:cc:dta1Device.MPOS" | sed 's|g7:cc:dta1Device.MPOS||g'`
    echo "Translation X stage position is "$transX
    set transY = `caget "g7:cc:dta2Device.MPOS" | sed 's|g7:cc:dta2Device.MPOS||g'`
    echo "Translation Y stage position is "$transY
    set transZ = `caget "g7:cc:dta3Device.MPOS" | sed 's|g7:cc:dta3Device.MPOS||g'`
    echo "Translation Z stage position is "$transZ

    echo "Saving data to g${filenumber}"

    #
    # Set the file name to the current time.
    #

#    set fileResponse = `setObserveFilename g7: g${filenumber}`
#    set fileStatus = `echo $fileResponse | grep 'Command Success'`
#    if ( $#fileStatus != 2 ) then
#	echo "Setting filename failed at "${observeTime}
#	exit -1
#    endif

    #
    # Make an observation
    #

    echo "Observing"
#    set observeResponse = `executeObserve g7:`
#    set observeStatus = `echo $observeResponse | grep 'Command Success'`
#    if ( $#observeStatus != 2 ) then
#	echo "Observation failed at "${observeTime}
#	exit -1
#    endif

    #
    # Log the filename, time, temps etc.
    #

    echo ${observeTime} g${filenumber} $filter1_pos1 $filter2_pos $temp0 $temp1 $temp2 $temp3 $temp4 $temp5 $temp6 $temp7 $temp8 $detTemp $crosstalkX $crosstalkY $thermalX $thermalY $thermalZ $transX $transY $transZ $resetTemp $offsetTemp $filteredTemp | cat >> ./logfiles/${day}/imageLog    

    @ filenumber += 1

    #
    # Move to the second filter wheel position.
    #

    echo ""
    echo "Moving to second filter wheel position..."
    set moveResponse = `moveAssembly g7:cc:fltAssembly $filter1_pos2 $filter2_pos`
    set moveStatus = `echo $moveResponse | grep 'Command Success'`
    if ( $#moveStatus != 2 ) then
    
	echo "Filter move failed"
	caget g7:cc:fltAssembly.MESS
	exit -1
    endif
    echo "Filter move succeeded"

    echo "Dummy move of translation assembly..."

    # We need to get one of the input parameters to feed back (MARK the record)

    set dtaA = `caget "g7:cc:dtaAssembly.A" | sed 's|g7:cc:dtaAssembly.A||g'`

    set moveResponse = `moveAssembly g7:cc:dtaAssembly ${dtaA}`
    set moveStatus = `echo $moveResponse | grep 'Command Success'`
    if ( $#moveStatus != 2 ) then
	echo "Assembly move failed"
	caget g7:cc:dtaAssembly.MESS
	exit -1
    endif
    echo "Translation stage move succeeded"

    set observeTime = `date +"%a %b %d %T %Y"`

    echo "Measuring temperatures at ${observeTime}"

    set temp0 = `caget "g7:cc:temp0.VAL" | sed 's|g7:cc:temp0.VAL||g'`
    echo "temp0 is "$temp0
    set temp1 = `caget "g7:cc:temp1.VAL" | sed 's|g7:cc:temp1.VAL||g'`
    echo "temp1 is "$temp1
    set temp2 = `caget "g7:cc:temp2.VAL" | sed 's|g7:cc:temp2.VAL||g'`
    echo "temp2 is "$temp2
    set temp3 = `caget "g7:cc:temp3.VAL" | sed 's|g7:cc:temp3.VAL||g'`
    echo "temp3 is "$temp3
    set temp4 = `caget "g7:cc:temp4.VAL" | sed 's|g7:cc:temp4.VAL||g'`
    echo "temp4 is "$temp4
    set temp5 = `caget "g7:cc:temp5.VAL" | sed 's|g7:cc:temp5.VAL||g'`
    echo "temp5 is "$temp5
    set temp6 = `caget "g7:cc:temp6.VAL" | sed 's|g7:cc:temp6.VAL||g'`
    echo "temp6 is "$temp6
    set temp7 = `caget "g7:cc:temp7.VAL" | sed 's|g7:cc:temp7.VAL||g'`
    echo "temp7 is "$temp7
    set temp8 = `caget "g7:cc:temp8.VAL" | sed 's|g7:cc:temp8.VAL||g'`
    echo "temp8 is "$temp8
    set detTemp = `caget "g7:sad:dc:detTemp.VAL" | sed 's|g7:sad:dc:detTemp.VAL||g'`
    echo "detector temp is "$detTemp
    set thermalX = `caget "g7:cc:dtaAssembly.VALA" | sed 's|g7:cc:dtaAssembly.VALA||g'`
    echo "Calculated thermal X offset is "$thermalX
    set thermalY = `caget "g7:cc:dtaAssembly.VALB" | sed 's|g7:cc:dtaAssembly.VALB||g'`
    echo "Calculated thermal Y offset is "$thermalY
    set thermalZ = `caget "g7:cc:dtaAssembly.VALC" | sed 's|g7:cc:dtaAssembly.VALC||g'`
    echo "Calculated thermal Z offset is "$thermalZ
    set   resetTemp = `caget "g7:cc:dtaresetTemp.VAL" | sed 's|g7:cc:dtaresetTemp.VAL||g'`
    echo "Zero thermal offset temp is "$resetTemp
    set   offsetTemp = `caget "g7:cc:dtaoffsetTemp.VAL" | sed 's|g7:cc:dtaoffsetTemp.VAL||g'`
    echo "Thermal offset temp is "$offsetTemp
    set   filteredTemp = `caget "g7:cc:dtafilteredTemp.VAL" | sed 's|g7:cc:dtafilteredTemp.VAL||g'`
    echo "Thermal offset temp (filtered) is "$filteredTemp
    set   crosstalkX = `caget "g7:cc:dtacrossx.VAL" | sed 's|g7:cc:dtacrossx.VAL||g'`
    echo "Calculated x-talk X offset is "$crosstalkX
    set   crosstalkY = `caget "g7:cc:dtacrossy.VAL" | sed 's|g7:cc:dtacrossy.VAL||g'`
    echo "Calculated x-talk Y offset is "$crosstalkY
    set transX = `caget "g7:cc:dta1Device.MPOS" | sed 's|g7:cc:dta1Device.MPOS||g'`
    echo "Translation X stage position is "$transX
    set transY = `caget "g7:cc:dta2Device.MPOS" | sed 's|g7:cc:dta2Device.MPOS||g'`
    echo "Translation Y stage position is "$transY
    set transZ = `caget "g7:cc:dta3Device.MPOS" | sed 's|g7:cc:dta3Device.MPOS||g'`
    echo "Translation Z stage position is "$transZ

    echo "Saving data to g${filenumber}"

    #
    # Set the file name to the current time.
    #

#    set fileResponse = `setObserveFilename g7: g${filenumber}`
#    set fileStatus = `echo $fileResponse | grep 'Command Success'`
#    if ( $#fileStatus != 2 ) then
#	echo "Setting filename failed at "${observeTime}
#	exit -1
#    endif

    #
    # Make an observation
    #

    echo "Observing"
#    set observeResponse = `executeObserve g7:`
#    set observeStatus = `echo $observeResponse | grep 'Command Success'`
#    if ( $#observeStatus != 2 ) then
#	echo "Observation failed at "${observeTime}
#	exit -1
#    endif


    #
    # Log the filename, time, temps etc.
    #

    echo ${observeTime} g${filenumber} $filter1_pos2 $filter2_pos $temp0 $temp1 $temp2 $temp3 $temp4 $temp5 $temp6 $temp7 $temp8 $detTemp $crosstalkX $crosstalkY $thermalX $thermalY $thermalZ $transX $transY $transZ $resetTemp $offsetTemp $filteredTemp | cat >> ./logfiles/${day}/imageLog    

    @ filenumber += 1

    #
    # Move to the third filter wheel position.
    #

    echo ""
    echo "Moving to third filter wheel position..."
    set moveResponse = `moveAssembly g7:cc:fltAssembly $filter1_pos3 $filter2_pos`
    set moveStatus = `echo $moveResponse | grep 'Command Success'`
    if ( $#moveStatus != 2 ) then

    echo "Filter move failed"
    caget g7:cc:fltAssembly.MESS
    exit -1
    endif
    echo "Filter move succeeded"

    echo "Dummy move of translation assembly..."

    # We need to get one of the input parameters to feed back (MARK the record)

    set dtaA = `caget "g7:cc:dtaAssembly.A" | sed 's|g7:cc:dtaAssembly.A||g'`

    set moveResponse = `moveAssembly g7:cc:dtaAssembly ${dtaA}`
    set moveStatus = `echo $moveResponse | grep 'Command Success'`
    if ( $#moveStatus != 2 ) then
	echo "Assembly move failed"
	caget g7:cc:dtaAssembly.MESS
	exit -1
    endif
    echo "Translation stage move succeeded"

    set observeTime = `date +"%a %b %d %T %Y"`

    echo "Measuring temperatures at ${observeTime}"

    set temp0 = `caget "g7:cc:temp0.VAL" | sed 's|g7:cc:temp0.VAL||g'`
    echo "temp0 is "$temp0
    set temp1 = `caget "g7:cc:temp1.VAL" | sed 's|g7:cc:temp1.VAL||g'`
    echo "temp1 is "$temp1
    set temp2 = `caget "g7:cc:temp2.VAL" | sed 's|g7:cc:temp2.VAL||g'`
    echo "temp2 is "$temp2
    set temp3 = `caget "g7:cc:temp3.VAL" | sed 's|g7:cc:temp3.VAL||g'`
    echo "temp3 is "$temp3
    set temp4 = `caget "g7:cc:temp4.VAL" | sed 's|g7:cc:temp4.VAL||g'`
    echo "temp4 is "$temp4
    set temp5 = `caget "g7:cc:temp5.VAL" | sed 's|g7:cc:temp5.VAL||g'`
    echo "temp5 is "$temp5
    set temp6 = `caget "g7:cc:temp6.VAL" | sed 's|g7:cc:temp6.VAL||g'`
    echo "temp6 is "$temp6
    set temp7 = `caget "g7:cc:temp7.VAL" | sed 's|g7:cc:temp7.VAL||g'`
    echo "temp7 is "$temp7
    set temp8 = `caget "g7:cc:temp8.VAL" | sed 's|g7:cc:temp8.VAL||g'`
    echo "temp8 is "$temp8
    set detTemp = `caget "g7:sad:dc:detTemp.VAL" | sed 's|g7:sad:dc:detTemp.VAL||g'`
    echo "detector temp is "$detTemp
    set thermalX = `caget "g7:cc:dtaAssembly.VALA" | sed 's|g7:cc:dtaAssembly.VALA||g'`
    echo "Calculated thermal X offset is "$thermalX
    set thermalY = `caget "g7:cc:dtaAssembly.VALB" | sed 's|g7:cc:dtaAssembly.VALB||g'`
    echo "Calculated thermal Y offset is "$thermalY
    set thermalZ = `caget "g7:cc:dtaAssembly.VALC" | sed 's|g7:cc:dtaAssembly.VALC||g'`
    echo "Calculated thermal Z offset is "$thermalZ
    set   resetTemp = `caget "g7:cc:dtaresetTemp.VAL" | sed 's|g7:cc:dtaresetTemp.VAL||g'`
    echo "Zero thermal offset temp is "$resetTemp
    set   offsetTemp = `caget "g7:cc:dtaoffsetTemp.VAL" | sed 's|g7:cc:dtaoffsetTemp.VAL||g'`
    echo "Thermal offset temp is "$offsetTemp
    set   filteredTemp = `caget "g7:cc:dtafilteredTemp.VAL" | sed 's|g7:cc:dtafilteredTemp.VAL||g'`
    echo "Thermal offset temp (filtered) is "$filteredTemp
    set   crosstalkX = `caget "g7:cc:dtacrossx.VAL" | sed 's|g7:cc:dtacrossx.VAL||g'`
    echo "Calculated x-talk X offset is "$crosstalkX
    set   crosstalkY = `caget "g7:cc:dtacrossy.VAL" | sed 's|g7:cc:dtacrossy.VAL||g'`
    echo "Calculated x-talk Y offset is "$crosstalkY
    set transX = `caget "g7:cc:dta1Device.MPOS" | sed 's|g7:cc:dta1Device.MPOS||g'`
    echo "Translation X stage position is "$transX
    set transY = `caget "g7:cc:dta2Device.MPOS" | sed 's|g7:cc:dta2Device.MPOS||g'`
    echo "Translation Y stage position is "$transY
    set transZ = `caget "g7:cc:dta3Device.MPOS" | sed 's|g7:cc:dta3Device.MPOS||g'`
    echo "Translation Z stage position is "$transZ

    echo "Saving data to g${filenumber}"

    #
    # Set the file name to the current time.
    #

#    set fileResponse = `setObserveFilename g7: g${filenumber}`
#    set fileStatus = `echo $fileResponse | grep 'Command Success'`
#    if ( $#fileStatus != 2 ) then
#	echo "Setting filename failed at "${observeTime}
#	exit -1
#    endif

    #
    # Make an observation
    #

    echo "Observing"
#    set observeResponse = `executeObserve g7:`
#    set observeStatus = `echo $observeResponse | grep 'Command Success'`
#    if ( $#observeStatus != 2 ) then
#	echo "Observation failed at "${observeTime}
#	exit -1
#    endif

    #
    # Log the filename, time, temps etc.
    #
    
    echo ${observeTime} g${filenumber} $filter1_pos3 $filter2_pos $temp0 $temp1 $temp2 $temp3 $temp4 $temp5 $temp6 $temp7 $temp8 $detTemp $crosstalkX $crosstalkY $thermalX $thermalY $thermalZ $transX $transY $transZ $resetTemp $offsetTemp $filteredTemp | cat >> ./logfiles/${day}/imageLog

    @ filenumber += 1

    set repetitions = $2
    set repsDone    = 0

    while ($repsDone < $repetitions)

	@ repsDone += 1
	echo ""
	echo "Repetition "$repsDone" of the clear images"

	#
	# Jiggle the grating
	#

	echo "Jiggling the grating to remove residual stresses."
	echo "Tilt away..."

	set moveResponse = `moveAssembly g7:cc:grAssembly 0 ${gratingID} ${jiggleAngle}`
	set moveStatus = `echo $moveResponse | grep 'Command Success'`
	if ( $#moveStatus != 2 ) then
	    echo "Grating assembly move 1 failed"
	    caget g7:cc:grAssembly.MESS
	    exit -1
	endif
	echo "Grating assembly move 1 succeeded"


	echo "Tilt back..."
	set moveResponse = `moveAssembly g7:cc:grAssembly 0 ${gratingID} ${imagingAngle}`
	set moveStatus = `echo $moveResponse | grep 'Command Success'`
	if ( $#moveStatus != 2 ) then
	    echo "Grating assembly move 2 failed"
	    caget g7:cc:grAssembly.MESS
	    exit -1
	endif
	echo "Grating assembly move 2 succeeded"

	echo "Dummy move of translation assembly..."

	# We need to get one of the input parameters to feed back (MARK the record)

	set dtaA = `caget "g7:cc:dtaAssembly.A" | sed 's|g7:cc:dtaAssembly.A||g'`

	set moveResponse = `moveAssembly g7:cc:dtaAssembly ${dtaA}`
	set moveStatus = `echo $moveResponse | grep 'Command Success'`
	if ( $#moveStatus != 2 ) then
	    echo "Assembly move failed"
	    caget g7:cc:dtaAssembly.MESS
	    exit -1
	endif
	echo "Translation stage move succeeded"

	set observeTime = `date +"%a %b %d %T %Y"`

	echo "Measuring temperatures at ${observeTime}"

	set temp0 = `caget "g7:cc:temp0.VAL" | sed 's|g7:cc:temp0.VAL||g'`
	echo "temp0 is "$temp0
	set temp1 = `caget "g7:cc:temp1.VAL" | sed 's|g7:cc:temp1.VAL||g'`
	echo "temp1 is "$temp1
	set temp2 = `caget "g7:cc:temp2.VAL" | sed 's|g7:cc:temp2.VAL||g'`
	echo "temp2 is "$temp2
	set temp3 = `caget "g7:cc:temp3.VAL" | sed 's|g7:cc:temp3.VAL||g'`
	echo "temp3 is "$temp3
	set temp4 = `caget "g7:cc:temp4.VAL" | sed 's|g7:cc:temp4.VAL||g'`
	echo "temp4 is "$temp4
	set temp5 = `caget "g7:cc:temp5.VAL" | sed 's|g7:cc:temp5.VAL||g'`
	echo "temp5 is "$temp5
	set temp6 = `caget "g7:cc:temp6.VAL" | sed 's|g7:cc:temp6.VAL||g'`
	echo "temp6 is "$temp6
	set temp7 = `caget "g7:cc:temp7.VAL" | sed 's|g7:cc:temp7.VAL||g'`
	echo "temp7 is "$temp7
	set temp8 = `caget "g7:cc:temp8.VAL" | sed 's|g7:cc:temp8.VAL||g'`
	echo "temp8 is "$temp8
	set detTemp = `caget "g7:sad:dc:detTemp.VAL" | sed 's|g7:sad:dc:detTemp.VAL||g'`
	echo "detector temp is "$detTemp
	set thermalX = `caget "g7:cc:dtaAssembly.VALA" | sed 's|g7:cc:dtaAssembly.VALA||g'`
	echo "Calculated thermal X offset is "$thermalX
	set thermalY = `caget "g7:cc:dtaAssembly.VALB" | sed 's|g7:cc:dtaAssembly.VALB||g'`
	echo "Calculated thermal Y offset is "$thermalY
	set thermalZ = `caget "g7:cc:dtaAssembly.VALC" | sed 's|g7:cc:dtaAssembly.VALC||g'`
	echo "Calculated thermal Z offset is "$thermalZ
	set   resetTemp = `caget "g7:cc:dtaresetTemp.VAL" | sed 's|g7:cc:dtaresetTemp.VAL||g'`
	echo "Zero thermal offset temp is "$resetTemp
	set   offsetTemp = `caget "g7:cc:dtaoffsetTemp.VAL" | sed 's|g7:cc:dtaoffsetTemp.VAL||g'`
	echo "Thermal offset temp is "$offsetTemp
	set   filteredTemp = `caget "g7:cc:dtafilteredTemp.VAL" | sed 's|g7:cc:dtafilteredTemp.VAL||g'`
	echo "Thermal offset temp (filtered) is "$filteredTemp
	set   crosstalkX = `caget "g7:cc:dtacrossx.VAL" | sed 's|g7:cc:dtacrossx.VAL||g'`
	echo "Calculated x-talk X offset is "$crosstalkX
	set   crosstalkY = `caget "g7:cc:dtacrossy.VAL" | sed 's|g7:cc:dtacrossy.VAL||g'`
	echo "Calculated x-talk Y offset is "$crosstalkY
	set transX = `caget "g7:cc:dta1Device.MPOS" | sed 's|g7:cc:dta1Device.MPOS||g'`
	echo "Translation X stage position is "$transX
	set transY = `caget "g7:cc:dta2Device.MPOS" | sed 's|g7:cc:dta2Device.MPOS||g'`
	echo "Translation Y stage position is "$transY
	set transZ = `caget "g7:cc:dta3Device.MPOS" | sed 's|g7:cc:dta3Device.MPOS||g'`
	echo "Translation Z stage position is "$transZ

	echo "Saving data to g${filenumber}"

	#
	# Set the file name to the current time.
	#

#	set fileResponse = `setObserveFilename g7: g${filenumber}`
#	set fileStatus = `echo $fileResponse | grep 'Command Success'`
#	if ( $#fileStatus != 2 ) then
#	    echo "Setting filename failed at "${observeTime}
#	    exit -1
#	endif

	#
	# Make an observation
	#

	echo "Observing"
#	set observeResponse = `executeObserve g7:`
#	set observeStatus = `echo $observeResponse | grep 'Command Success'`
#	if ( $#observeStatus != 2 ) then
#	    echo "Observation failed at "${observeTime}
#	    exit -1
#	endif

	#
	# Log the filename, time, temps etc.
	#

	echo ${observeTime} g${filenumber} $filter1_pos3 $filter2_pos $temp0 $temp1 $temp2 $temp3 $temp4 $temp5 $temp6 $temp7 $temp8 $detTemp $crosstalkX $crosstalkY $thermalX $thermalY $thermalZ $transX $transY $transZ $resetTemp $offsetTemp $filteredTemp | cat >> ./logfiles/${day}/imageLog

	@ filenumber += 1

    end
    
    echo ""
    echo "The time is now "`date +"%T"`
    echo "Type Ctrl-c to stop the script."
    echo "Waiting for ${intervalSeconds} seconds..."
    sleep $intervalSeconds

end

exit






