# Include file identifying the target architecture (defines the T_A
# macro) and application configuration definitions

include ../.applTop
include $(APPLIC_TOP)/config/CONFIG

# External libraries on which this directory is dependent.
# DEPLIBS      =

# User compiler and loader flags
# SNC_FLAGS    =
# USR_CFLAGS   =
# USR_INCLUDES =
# USR_LDFLAGS  =
# USR_LDLIBS   =

# Add the record include (*.h) files to this variable.
# This causes the record *.h file to be built from the record *.dbd file.
RECTYPES =

# Add dbd files to this variable for installation.
DBDINSTALL =

# Add the source code files to this variable. The default has all .c files 
SRCS.c	= $(wildcard ../*.c) 

# Add the object files in one of these two variables. 
LIBOBJS +=

#OBJS	=  $(strip $(patsubst ../%.c,    %.o, $(SRCS.c))             \
		   $(patsubst ../%.st,   %.o, $(wildcard ../*.st  )) \
                   $(patsubst ../%.stpp, %.o, $(wildcard ../*.stpp)))

# Standard macros for files which are to be built and installed.
# PROD (products) and SCRIPTS are installed in INSTALL_BIN
PROD	= $(strip $(patsubst %.o, %, $(OBJS))                        \
		  $(patsubst ../%.vws, %, $(wildcard ../*.vws)))
SCRIPTS	=

# LIBNAME is installed in INSTALL_LIB
LIBNAME	=

# INC is installed in INSTALL_INCLUDE
INC	=

# MAN1 is installed in INSTALL_MAN/man1
MAN1	=

# DOCS are installed in INSTALL_DOC
DOCS	=

# DATA are installed in INSTALL_DATA
DATA  = ../probePko.lut
DATA += ../probeBas.lut
DATA += ../mskSim.lut
DATA += ../mskRel.lut
DATA += ../mskGrp.lut
DATA += ../mskCas.lut
DATA += ../msk.lut
DATA += ../masks.lut
DATA += ../lambdaFocus.lut
DATA += ../grt.lut
DATA += ../gratings.lut
DATA += ../gr_TEST.lut
DATA += ../grD.lut
DATA += ../grC.lut
DATA += ../grB.lut
DATA += ../grA.lut
DATA += ../gr.lut
DATA += ../garbage.lut
DATA += ../flt2.lut
DATA += ../flt1.lut
DATA += ../flt.lut
DATA += ../filters.lut
DATA += ../dta3.lut
DATA += ../dta2.lut
DATA += ../dta1.lut
DATA += ../dta.lut
DATA += ../aux_gr.lut
DATA += ../atmExp.lut
DATA += ../atmEnp.lut
DATA += ../atm.lut
DATA += ../mskExt.lut

# Any extra targets can be placed in a TARGETS macro (the build target
# builds only pre_build, LIBNAME, TARGETS and PROD, not SCRIPTS, INC etc)
TARGETS	=

# Rules for building targets
include $(APPLIC_TOP)/config/RULES.Build

# There is no product rule, but one can be added and edited.
#$(PROD): $(OBJS)
#	$(RM) $@
#	$(LINK.c) $@ $(OBJS)
