#!/bin/csh -f
#
# Script to log GMOS temperatures every 5 minutes
#

echo " "
echo "Logging GMOS temperatures - Mauna Kea Instrument"
echo "This script will run forever. Terminate with CTRL/C"
echo " "

while (1)

   date
   caget gm:cc:temp0
   caget gm:cc:temp1
   caget gm:cc:temp2
   caget gm:cc:temp3
   caget gm:cc:temp4
   caget gm:cc:temp5
   caget gm:cc:temp6
   caget gm:cc:temp7
   caget gm:cc:temp8
   sleep 300

end
