#!/usr/local/bin/tcsh -f
#
# Name: assemblyCommand
#
# Purpose: 
#	To start an Assembly record command and monitor its
#	progress.
#
# Assumptions:
#       DAR_DIR_START = 3
#       assembly record success status = 0
#

set dirResponse = `caput $1 "3"`

set ackResponse = `caget $2 | grep $2 | grep 0`

if ( $#ackResponse != 2 ) then
        set assname = `basename $1 .VAL`
        set errmsg = `caget -t ${assname}.MESS`
	echo "Command rejected - $errmsg"
	exit
endif


while ( 1 )

	sleep 1

	set busyResponse = `caget $3`

	set commandDone = `echo $busyResponse | grep $3 | grep IDLE`
	if ( $#commandDone == 2 ) then
		echo "Command Success"
		exit
	endif

	set commandFailed = `echo $busyResponse | grep $3 | grep ERR`
	if ( $#commandFailed == 2 ) then
                set assname = `basename $3 .BUSY`
                set errmsg = `caget -t ${assname}.MESS`
		echo "Command Failed - $errmsg"
		exit
	endif

end

exit
