#!/usr/local/bin/tcsh -f
#
# Name: executeApplyCommand
#
# Purpose: 
#	To start a CAD/CAR record command via the "apply" record
#
# Invocation:
#       executeApplyCommand cadrecord applyrecord response carrecord
#
# Assumptions:
#       CAD_MARK  = 0
#       CAD_CLEAR = 1
#       CAD_START = 3
#       CAD record success status = 0
#
# Deficiencies:
#       Arbitrary time delays have to be included to allow the apply
#       record protocol to work.
#

# Clear the apply record before starting and wait for it to propagate
set dirResponse = `caput $2 "1"`
sleep 1

# Mark the CAD record and START the apply record
set dirResponse = `caput $1 "0"`
set dirResponse = `caput $2 "3"`

set ackResponse = `caget $3 | grep $3 | grep 0`

if ( $#ackResponse != 2 ) then
        set cadname = `basename $3 .VAL`
        set errmsg = `caget -t ${cadname}.MESS`
	echo "Command rejected - $errmsg"
	exit
endif


while ( 1 )

	sleep 1

	set busyResponse = `caget $4`

	set commandDone = `echo $busyResponse | grep $4 | grep IDLE`
	if ( $#commandDone == 2 ) then
		echo "Command Success"
		exit
	endif

	set commandFailed = `echo $busyResponse | grep $4 | grep ERR`
	if ( $#commandFailed == 2 ) then
                set carname = `basename $4 .VAL`
                set errmsg = `caget -t ${carname}.OMSS`
		echo "Command Failed - $errmsg"
		exit
	endif

end

exit
