#!/usr/local/bin/tcsh -f
#
# Name: getLastMaskId
#
# Purpose: 
#	To recover the last mask ID from the lookup table and 
#	load it into the assembly record
#

set updateLine = `tail -1 $2`
if ( $#updateLine != 3 ) then
	echo "Update file parse error - is the last line blank"
	exit
endif

set response = `caput $1 $updateLine[3] | grep $1 | grep $updateLine[3]`

if ( $#response == 0 ) then
	echo "Can not set mask ID"
	exit
endif

echo "Command Success"
exit

