#!/usr/local/bin/tcsh -f
#
# Name: lifterExhaust
#
# Purpose: 
#	To activate the lifter exhaust for a few seconds.
#       This primitive may be used to guard against leaks
#       into the grating lifter while running a checkout
#       script.
#
# Invocation:
#       lifterExhaust gm:
#
# Assumptions:
#       The switch requires 0 to activate and 1 to deactivate
#

#
# This script would be dangerous to execute on the MK hardware by accident,
# so add a safety check.
#

if ( ($1 == "gm:") && !($?GMOS_MK_ACCESS)) then
    echo ""
    echo "GMOS MK safety check failed."
    echo ""
    echo "Before executing this script, which will move real MK hardware,"
    echo 'you must type "gmosMK" to confirm that it is safe to do so.'
    echo ""
    exit
endif

set caResponse = `caput ${1}cc:grDownValve "0"`

sleep 5

set caResponse = `caput ${1}cc:grDownValve "1"`

exit
