#!/usr/local/bin/tcsh -f
#
# Name: moveAssembly
#
# Purpose: 
#	To configure a GMOS assembly
#
# Invocation:
#       moveAssembly assembly A [B C D E]
#
# Assumptions:
#       DAR_MODE_MOVE = 1
#       The assemblyCommand script is available in the current PATH
#

#
# Check at least two arguments have been supplied
#

if ($#argv < 2) then
    echo "moveAssembly: Please supply at least two arguments - assembly name and position"
    exit -1
endif

#
# Set the assembly into MOVE mode
#

set caputResponse = `caput ${1}.MODE "1"`

#
# Write the desired arguments, depending on how many have
# been supplied with the script.
#

set caputResponse = `caput ${1}.A $2`

if ( $#argv >= 3 ) then

   set caputResponse = `caput ${1}.B $3`
endif

if ( $#argv >= 4 ) then

   set caputResponse = `caput ${1}.C $4`
endif

if ( $#argv >= 5 ) then

   set caputResponse = `caput ${1}.D $5`
endif

if ( $#argv >= 6 ) then

   set caputResponse = `caput ${1}.E $6`
endif

#
# Execute the move
#

set assemblyResponse = `assemblyCommand ${1}.DIR ${1}.VAL ${1}.BUSY`

set okay = `echo $assemblyResponse | grep 'Command Success'`

if ( $#okay == 2 ) then
    echo "Command Success"
    exit
else
    echo $assemblyResponse
    exit -1
endif

exit
