#!/usr/local/bin/tcsh -f
#
# Name: stopCommand
#
# Purpose: 
#	To stop a CAD/CAR command 
#
# Assumptions:
#       CAD_MARK = 0
#       CAD_STOP = 4
#       CAD record success status = 0
#

set dirResponse = `caput $1 "0"`
set dirResponse = `caput $1 "4"`

set ackResponse = `caget $2 | grep $2 | grep 0`

if ( $#ackResponse != 2 ) then
	echo "Stop Command Rejected"
	exit
endif

echo "Command Stopping"
exit
