
include ../.applTop
include $(APPLIC_TOP)/config/CONFIG
ADL2DL = $(EPICS)/extensions/bin/solaris/adl2dl2-4

SCRIPTS = gmosCcStartMKRR gmosCcStartMKRS gmosCcStartMKSR gmosCcStartMKSS \
	  gmosCcStartCP gmEditFile gmEditFileField gmCcDoCommand \
	  gmSeqStart gmSeqStartMKRR gmSeqDoCommand gmSeqCcCommand \
          gmosStartMKRR gmosStartMKSS gmosStartMKSS2 gmosStartCP \
	  gmosStart gmosStartMK gmosAlarm gmosCcAlarm gmosDcAlarm \
	  gmosXterm gmosIocConsole gmosIocAnnex sim2 gmoscc gmosdc \
	  gmosannex gmosLog gmosSetResetAliases gmosHelp gmosTest

# List of display (*.dl) files
#DATA    = ../gmos_logo.gif ../colors.dl ../gmColors.dl $(wildcard ../*.dl) \
#          $(patsubst ../%.adl, %.dl, $(wildcard ../*.adl ../*.bit ../*.tk \
#	  ../*.sh ../*.test))


DATA = colors.dl gmColors.dl \
	$(patsubst ../%.adl, %.dl, $(wildcard ../*.adl ../*.bit ../*.gif ../*.tk \
          ../*.sh ../*.test))

include $(APPLIC_TOP)/config/RULES.Build

# Override system rules for creating dl files

%.dl: ../%.adl
	$(RM) $@
	-$(ADL2DL) $< >/dev/null

%.dl: %.adl
	$(RM) $@
	-$(ADL2DL) $< >/dev/null
